### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by henninghorn** [Henrikschytze/Chat-Project#1]
https://github.com/Henrikschytze/Chat-Project/blob/eec76cfeac377d7a0cf8f5d889051e80af371619/app.js#L190-L225

Search does not seem to work. You should not return the result array within the array's built-in .forEach method

**Comment by Stalkcomrade** [comment]
It is weird, just checked: it.

![image](https://user-images.githubusercontent.com/7871234/37605465-871f87ba-2b93-11e8-8a7b-602df7faa872.png)

Yeah, but the final output is filtered afterwards - it is not purely a forEach return - is it still not the solution?

`let final = results_search.filter(el => el != -1); 
     console.log(final); 
`

**Comment by henninghorn** [comment]
@Stalkcomrade 
Oh, yeah, it does actually work. I temporarily only logged out errors in my browser.
You could still make it a bit more cleaner. And currently you are not returning the whole message object, only the actual input.
